### ISSUE TITLE
add to d2 README

### ISSUE THREAD

**Issue by andorsk** [andorsk/d2-mode#18]
add d2-mode to D2 README after milestone 1.

**Comment by alixander** [comment]
happy to add now if ok with you, looks like a working solution!

**Comment by andorsk** [comment]
Here's the patch I was going to submit: https://github.com/terrastruct/d2/compare/master...andorsk:d2:patch-1

**Comment by alixander** [comment]
I made a PR to include a batch of plugins in the README and threw yours in (https://github.com/terrastruct/d2#community-plugins). I think even if it's not fully ready, it'll hopefully drive help to this project. Plus I know there's many Emacs users for D2 who'd be happy to see that there's substantial progress already made here. (if you'd like me to revert, totally understand, just let me know!).

**Comment by andorsk** [comment]
@alixander sounds good. Can you make a small modification: https://github.com/terrastruct/d2/pull/422

**Comment by andorsk** [comment]
closing.
