### ISSUE TITLE
void function d2-indent-line

### ISSUE THREAD

**Issue by suliveevil** [andorsk/d2-mode#22]
It only happens when I start Emacs with my config:

1. start Emacs
2. change scratch buffer's mode to d2-mode
3. keystroke Return/Enter

![d2-indent-line](https://user-images.githubusercontent.com/35763237/205260257-4f6ff9f5-4df1-4800-9ef8-50849f49ad6f.png)

When using `emacs -Q -l d2-mode.el`, the problem disappears.

Would you please help me out? Thank you very much.

**Comment by andorsk** [comment]
Thanks @suliveevil! Super helpful that you've provided this input. I've made a fix in #23. Can you let me know if it's resolved now!

**Comment by suliveevil** [comment]
Thank you very much. 🥰

**Comment by andorsk** [comment]
Thank you for the issue submission! It's so hard to catch these things without your support!

**Comment by suliveevil** [comment]
I'm glad i can make some help😬
