### ISSUE TITLE
Comment syntax

### ISSUE THREAD

**Issue by ashlineldridge** [andorsk/d2-mode#41]
I'm relatively new to D2 but is there a reason `d2-mode` uses `%%` for comments rather than [the standard](https://d2lang.com/tour/comments) `#`?

**Comment by andorsk** [comment]
Good question. Comments should be consistent with https://d2lang.com/tour/comments/. This could be a mistake.

**Comment by andorsk** [comment]
Fixed in https://github.com/andorsk/d2-mode/pull/42

**Comment by ashlineldridge** [comment]
@andorsk Thanks for addressing this so quickly! 🙇‍♂️
