### ISSUE TITLE
Indentation Not Working

### ISSUE THREAD

**Issue by joyguar** [andorsk/d2-mode#45]
Hello,

I've just installed and tried making use of `d2-mode` but indentation isn't working. If I type out the example
```
My Class {
   shape: class
   +field: string
   read ()
}
```
indentation behaves the same as in fundamental mode. I have to manually tab the `shape: class` line, and then I have to manually de-indent the curly brace. I've installed both from melpa and tried a git clone, but I get the same behavior. 

Are there limits on the indentation?

**Comment by andorsk** [comment]
Thanks for raising this @Cloudcolour. I don't think there's any specific indentation policies set yet, so I think you're right, this can be a feature request that can be added in.

**Comment by MoisMoshev** [comment]
I'm willing to take on that, if I get any idea of how indentation works. Is there a simple mode that does it, which I can look at for inspiration?
I'm reasonably comfortable in emacs lisp.

**Comment by andorsk** [comment]
hey Moises. Sorry for the delay in a response here. https://github.com/abrochard/mermaid-mode/blob/master/mermaid-mode.el#L133 is a good starting point and I would certainly welcome the contribution!

**Comment by MoisMoshev** [comment]
Ooh that's nice. Moving point and then searching backwards, I hadn't thought of that.
Let me see when I'll fit it in the schedule.

**Comment by MoisMoshev** [comment]
There is still an issue with lines such as the following
`  user_id: text {constraint: foreign_key}`
where the opening and closing brace are on the same line. This throws off indentation in subsequent lines. Let me see if I can fix this.
